export const members = [
    {
        name: "Melissa",
        teamType: "team",
        id: 1,
        title: "Founder",
        bio: "Professional writer and businesswoman with over 10 years of experience in publishing, marketing and developing technology-driven writing products. Mel Writes about blockchain, lifestyle, travel and how it affects our everyday lives. She is very passionate about storytelling and building community. She holds a BA in Political Science from The George Washington University and currently resides in Miami, Florida.",
        website: "",
        facebook: "",
        twitter: "melwritesmiami",
        linkedIn: "melissa-a-henderson-",
        photo: "https://i.imgur.com/sQ78S1P.jpg",
    },
    {
        name: "Jess",
        teamType: "team",
        id: 2,
        title: "Design Partner",
        bio: "With a passion for blending creativity and technology, Jess has found her niche in the world of blockchain, where she combines her expertise in design and her fascination with decentralized systems.",
        facebook: "",
        twitter: "thevioletverse",
        linkedIn: "",
        photo: "https://imgur.com/Hd5mm5t",
    },
    {
        name: "Avalon",
        teamType: "team",
        id: 3,
        title: "Editorial Partner",
        bio: "A professional writer with extensive experience in the media, communications, and tech industries. Her goal is to help clients build their  brand presence online.  From DJing a morning show on 91.1 WMUA to reporting the news in New Hampshire to working through the pandemic in New York City, Avalon has just about done it all.",
        website: "https://avalonlustick.com ",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://i.imgur.com/sLc5w7e.jpg",
    },
    {
        name: "Morgan",
        teamType: "team",
        id: 4,
        title: "Operations Partner",
        bio: "Over the past several years, Morgan has worked in the beauty and financial industry, cultivating relationships in the procurement and project management spaces. She brings her organizational and people management skills to Web3. She fell down the crypto rabbit hole in 2022 and is eager to work with creators of all forms.",
        facebook: "",
        twitter: "morgymorgg_nft",
        linkedIn: "",
        photo: "https://i.imgur.com/YraRGLa.png",
    },
    {
        name: "Prachi Modi",
        teamType: "contributor",
        id: 5,
        title: "New York, Serial Entrepreneur",
        bio: "I'm a Writer, Chef, Educator, and Blockchain Enthusiast. My career started off with working as an Analyst with KPMG and Goldman Sachs. While working in corporate finance, I came across Nobel Peace Laureate Muhammad Yunus. His theories around micro lending gave me the confidence to kick start a small business in Uganda, making it the most powerful start in my entrepreneurial journey. I truly believe blockchain technology has the ability to solve historical issues around the lack of documentation, credentials and credibility, and uncollateralized lending in emerging markets. My focus in web3 is building social entrepreneurship and innovation driven projects. ",
        website: "",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://cdn.discordapp.com/attachments/975860284377944124/1014352007563329606/prachi_headshot.jpeg",
    },
    {
        name: "Matthew Mills",
        teamType: "contributor",
        id: 6,
        title: "Contributor",
        bio: "Barcelona-based artist and creator.",
        website: "https://www.matthewmillsw.com/ ",
        instagram: "matthewmillsw",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://i.imgur.com/5F2jLP9.png",
    },
    {
        name: "Autumn Phaneuf",
        teamType: "contributor",
        id: 7,
        title: "Contributor",
        bio: "Autumn is an academic and tech/operations consultant by day and artist by night. Previously, she was CEO of her own biotech startup, and COO and Engineering Lead of a Web3 Marketing Agency and Protocol, Rising Tides. She is well known for her work in community building and DE&I initiatives. She has been recognized as an Influential Mover and Shaker in Blockchain by Startup Boston.  Her work has been featured with NSF, Des Femmes Magazine, Buidl Besties, Hexi NFT, Sunbirbs, Weird Wildflowers, Boston DAO, ETH Boston, Women in Blockchain, and many other brands.",
        website: "",
        facebook: "",
        twitter: "1autumn_leaf",
        linkedIn: "",
        photo: "https://cdn.discordapp.com/attachments/975860284377944124/1014352007051616317/-r29w3y.jpeg",
    },
    {
        name: "Van Wilhoite",
        teamType: "contributor",
        id: 8,
        title: "Contributor",
        bio: "Van is a cyber security professional with over 10 years of industry experience. He offers specialized cyber security consulting for individuals and businesses at naban.xyz.",
        website: "",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://i.imgur.com/jExOYle.png",
    },
];

/*This part is the users for the contributors*/

export const contributor = [
    {
        name: "Prachi Modi",
        id: 1,
        title: "New York, Serial Entrepreneur",
        bio: "I'm a Writer, Chef, Educator, and Blockchain Enthusiast. My career started off with working as an Analyst with KPMG and Goldman Sachs. While working in corporate finance, I came across Nobel Peace Laureate Muhammad Yunus. His theories around micro lending gave me the confidence to kick start a small business in Uganda, making it the most powerful start in my entrepreneurial journey. I truly believe blockchain technology has the ability to solve historical issues around the lack of documentation, credentials and credibility, and uncollateralized lending in emerging markets. My focus in web3 is building social entrepreneurship and innovation driven projects. ",
        website: "",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://cdn.discordapp.com/attachments/975860284377944124/1014352007563329606/prachi_headshot.jpeg",
    },
    {
        name: "Matthew Mills",
        id: 2,
        title: "Contributor",
        bio: "Barcelona-based artist and creator.",
        website: "https://www.matthewmillsw.com/ ",
        instagram: "matthewmillsw",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://i.imgur.com/5F2jLP9.png",
    },
    {
        name: "Autumn Phaneuf",
        id: 3,
        title: "Contributor",
        bio: "Autumn is an academic and tech/operations consultant by day and artist by night. Previously, she was CEO of her own biotech startup, and COO and Engineering Lead of a Web3 Marketing Agency and Protocol, Rising Tides. She is well known for her work in community building and DE&I initiatives. She has been recognized as an Influential Mover and Shaker in Blockchain by Startup Boston.  Her work has been featured with NSF, Des Femmes Magazine, Buidl Besties, Hexi NFT, Sunbirbs, Weird Wildflowers, Boston DAO, ETH Boston, Women in Blockchain, and many other brands.",
        website: "",
        facebook: "",
        twitter: "1autumn_leaf",
        linkedIn: "",
        photo: "https://cdn.discordapp.com/attachments/975860284377944124/1014352007051616317/-r29w3y.jpeg",
    },
    {
        name: "Van Wilhoite",
        id: 4,
        title: "Contributor",
        bio: "Van is a cyber security professional with over 10 years of industry experience. He offers specialized cyber security consulting for individuals and businesses at naban.xyz.",
        website: "",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "https://i.imgur.com/jExOYle.png",
    },
];
