export const members = [
    {
        name: "Melissa",
        id: 1,
        title: "Founder",
        website: "",
        facebook: "",
        twitter: "melwritesmiami",
        linkedIn: "melissa-a-henderson-",
        photo: "/team/Mel.jpg",
    },
    {
        name: "Dani",
        id: 2,
        title: "Design Partner",
        facebook: "",
        twitter: "koriixyz",
        linkedIn: "",
        photo: "/team/Dani.png",
    },
    {
        name: "Avalon",
        id: 3,
        title: "Editorial Partner",
        website: "https://avalonlustick.com ",
        facebook: "",
        twitter: "",
        linkedIn: "",
        photo: "/team/Avalon.png",
    },
    {
        name: "Morgan",
        id: 4,
        title: "Operations Partner",
        facebook: "",
        twitter: "morgymorgg_nft",
        linkedIn: "",
        photo: "/team/Morgan.png",
    },
];
