/**
 * Sample data for developer mode when CMS is disabled
 * 
 * Usage:
 * - Set USE_SAMPLE_DATA=true in your .env file to always use sample data
 * - Or sample data will automatically be used in development mode (NODE_ENV=development)
 * 
 * This allows you to work on UI without needing database connectivity.
 */

export const samplePosts = [
  {
    _id: 1,
    title: 'The Future of Decentralized Media',
    subtitle: 'Exploring how blockchain technology is reshaping content creation',
    category: 'Tech',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'the-future-of-decentralized-media-abc123',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-15').toISOString(),
    lastUpdated: new Date('2024-01-15').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 2,
    title: 'Sustainable Fashion in the Digital Age',
    subtitle: 'How technology is revolutionizing the fashion industry',
    category: 'Lifestyle',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'sustainable-fashion-digital-age-def456',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-20').toISOString(),
    lastUpdated: new Date('2024-01-20').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 3,
    title: 'Understanding Web3: A Beginner\'s Guide',
    subtitle: 'Everything you need to know about the decentralized web',
    category: 'Education',
    banner: '/banners/Photography_2.png',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    slug: 'understanding-web3-beginners-guide-ghi789',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-25').toISOString(),
    lastUpdated: new Date('2024-01-25').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 4,
    title: 'AI and Creative Expression',
    subtitle: 'Exploring the intersection of artificial intelligence and art',
    category: 'Tech',
    banner: '/banners/thumbnail.jpeg',
    video: null,
    slug: 'ai-creative-expression-jkl012',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-01').toISOString(),
    lastUpdated: new Date('2024-02-01').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 5,
    title: 'Wellness in the Metaverse',
    subtitle: 'How virtual spaces are transforming health and wellness',
    category: 'Lifestyle',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'wellness-metaverse-mno345',
    createdBy: 'user3',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-05').toISOString(),
    lastUpdated: new Date('2024-02-05').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 6,
    title: 'Blockchain Basics: What You Need to Know',
    subtitle: 'A comprehensive introduction to blockchain technology',
    category: 'Education',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'blockchain-basics-pqr678',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-10').toISOString(),
    lastUpdated: new Date('2024-02-10').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 7,
    title: 'NFTs and Digital Ownership',
    subtitle: 'Understanding non-fungible tokens and their impact',
    category: 'Tech',
    banner: '/banners/Photography_2.png',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    slug: 'nfts-digital-ownership-stu901',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-15').toISOString(),
    lastUpdated: new Date('2024-02-15').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 8,
    title: 'Mindful Living in a Digital World',
    subtitle: 'Finding balance between technology and well-being',
    category: 'Lifestyle',
    banner: '/banners/thumbnail.jpeg',
    video: null,
    slug: 'mindful-living-digital-world-vwx234',
    createdBy: 'user3',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-20').toISOString(),
    lastUpdated: new Date('2024-02-20').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 9,
    title: 'Getting Started with Flow Blockchain',
    subtitle: 'A practical guide to building on Flow',
    category: 'Education',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'getting-started-flow-blockchain-yza567',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-25').toISOString(),
    lastUpdated: new Date('2024-02-25').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 10,
    title: '[Draft] Upcoming Article on DeFi',
    subtitle: 'This is a draft article',
    category: 'Tech',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'draft-upcoming-article-defi-bcd890',
    createdBy: 'user2',
    contributor: null,
    hidden: true,
    created: new Date('2024-03-01').toISOString(),
    lastUpdated: new Date('2024-03-01').toISOString(),
    tokenPrice: null,
  },
]

export const sampleAuthors = [
  {
    userId: 'user1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    role: 'admin',
    username: 'alexj',
  },
  {
    userId: 'user2',
    name: 'Sam Martinez',
    email: 'sam@example.com',
    role: 'admin',
    username: 'samm',
  },
  {
    userId: 'user3',
    name: 'Jordan Lee',
    email: 'jordan@example.com',
    role: 'admin',
    username: 'jordanl',
  },
]

export const sampleContributors = [
  {
    userId: 'contributor1',
    name: 'Taylor Swift',
    email: 'taylor@example.com',
    role: 'contributor',
    username: 'taylors',
  },
  {
    userId: 'contributor2',
    name: 'Morgan Chen',
    email: 'morgan@example.com',
    role: 'contributor',
    username: 'morganc',
  },
]

