/**
 * Sample data for developer mode when CMS is disabled
 * 
 * Usage:
 * - Set USE_SAMPLE_DATA=true in your .env file to always use sample data
 * - Or sample data will automatically be used in development mode (NODE_ENV=development)
 * 
 * This allows you to work on UI without needing database connectivity.
 */

export const samplePosts = [
  {
    _id: 1,
    title: 'The Future of Decentralized Media',
    subtitle: 'Exploring how blockchain technology is reshaping content creation',
    category: 'Tech',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'the-future-of-decentralized-media-abc123',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-15').toISOString(),
    lastUpdated: new Date('2024-01-15').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 2,
    title: 'Sustainable Fashion in the Digital Age',
    subtitle: 'How technology is revolutionizing the fashion industry',
    category: 'Lifestyle',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'sustainable-fashion-digital-age-def456',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-20').toISOString(),
    lastUpdated: new Date('2024-01-20').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 3,
    title: 'Understanding Web3: A Beginner\'s Guide',
    subtitle: 'Everything you need to know about the decentralized web',
    category: 'Education',
    banner: '/banners/Photography_2.png',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    slug: 'understanding-web3-beginners-guide-ghi789',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-01-25').toISOString(),
    lastUpdated: new Date('2024-01-25').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 4,
    title: 'AI and Creative Expression',
    subtitle: 'Exploring the intersection of artificial intelligence and art',
    category: 'Tech',
    banner: '/banners/thumbnail.jpeg',
    video: null,
    slug: 'ai-creative-expression-jkl012',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-01').toISOString(),
    lastUpdated: new Date('2024-02-01').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 5,
    title: 'Wellness in the Metaverse',
    subtitle: 'How virtual spaces are transforming health and wellness',
    category: 'Lifestyle',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'wellness-metaverse-mno345',
    createdBy: 'user3',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-05').toISOString(),
    lastUpdated: new Date('2024-02-05').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 6,
    title: 'Blockchain Basics: What You Need to Know',
    subtitle: 'A comprehensive introduction to blockchain technology',
    category: 'Education',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'blockchain-basics-pqr678',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-10').toISOString(),
    lastUpdated: new Date('2024-02-10').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 7,
    title: 'NFTs and Digital Ownership',
    subtitle: 'Understanding non-fungible tokens and their impact',
    category: 'Tech',
    banner: '/banners/Photography_2.png',
    video: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    slug: 'nfts-digital-ownership-stu901',
    createdBy: 'user2',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-15').toISOString(),
    lastUpdated: new Date('2024-02-15').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 8,
    title: 'Mindful Living in a Digital World',
    subtitle: 'Finding balance between technology and well-being',
    category: 'Lifestyle',
    banner: '/banners/thumbnail.jpeg',
    video: null,
    slug: 'mindful-living-digital-world-vwx234',
    createdBy: 'user3',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-20').toISOString(),
    lastUpdated: new Date('2024-02-20').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 9,
    title: 'Getting Started with Flow Blockchain',
    subtitle: 'A practical guide to building on Flow',
    category: 'Education',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'getting-started-flow-blockchain-yza567',
    createdBy: 'user1',
    contributor: null,
    hidden: false,
    created: new Date('2024-02-25').toISOString(),
    lastUpdated: new Date('2024-02-25').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 10,
    title: '[Draft] Upcoming Article on DeFi',
    subtitle: 'This is a draft article',
    category: 'Tech',
    banner: '/banners/Photography_1.png',
    video: null,
    slug: 'draft-upcoming-article-defi-bcd890',
    createdBy: 'user2',
    contributor: null,
    hidden: true,
    created: new Date('2024-03-01').toISOString(),
    lastUpdated: new Date('2024-03-01').toISOString(),
    tokenPrice: null,
  },
  {
    _id: 11,
    title: 'Caribbean, Haitian & Black American Restaurant Guide',
    subtitle: 'Miami\'s hottest restaurants to taste the Black Diaspora',
    category: 'Lifestyle',
    banner: '/banners/large_banner.png',
    video: null,
    slug: 'testpost',
    createdBy: 'user4',
    contributor: null,
    hidden: false,
    created: new Date('2025-11-18').toISOString(),
    lastUpdated: new Date('2025-11-20').toISOString(),
    tokenPrice: null,
    tldr: 'Miami is known for its authentic cuisine. If you want to taste food from all over the Black diaspora -- from Haitian to Jamaican, Bahamian and more, Miami is the place to experience it all!',
    body: '<h2>🇭🇹 <strong>Haitian Restaurants</strong></h2><h3><strong>Jenny\'s Caribbean Restaurant</strong></h3><p>Authentic Haitian comfort classics — fried fish, plantains, and more.</p><p>🔗 <a href="https://www.jennyscaribbeanrestaurant.com/">https://www.jennyscaribbeanrestaurant.com/</a></p><h3><strong>Cecibon Restaurant</strong></h3><p>Home-style Haitian dishes, generous portions, known for soup joumou.</p><p>🔗 <a href="https://cecibonrestaurant.com/">https://cecibonrestaurant.com/</a></p><h3><strong>Piman Bouk Haitian Restaurant</strong></h3><p>Vibrant, flavorful stewed meats.</p><p>🔗 <a href="https://pimanbouk-miami.com/">https://pimanbouk-miami.com/</a></p><h3><strong>Naomi\'s Garden Restaurant & Lounge</strong></h3><p>Iconic Little Haiti gem with a lush outdoor garden.</p><p>🔗 <a href="https://naomisgarden.com/">https://naomisgarden.com/</a></p><h3><strong>Manjay Restaurant (Wynwood)</strong></h3><p>Modern Caribbean street food — griot tacos, bowls, and sandwiches.</p><p>🔗 <a href="https://www.manjayrestaurant.com/">https://www.manjayrestaurant.com/</a></p><h2>🇯🇲 <strong>Caribbean / Jamaican Restaurants</strong></h2><h3><strong>Greg\'s Cookout</strong></h3><p>BBQ + Caribbean fusion; jerk chicken, ribs, comfort sides.</p><p>🔗 <a href="https://gregscookout.com/">https://gregscookout.com/</a></p><h3><strong>Clive\'s Café</strong></h3><p>A Miami institution famous for oxtail, curry goat, and rice & peas.</p><p>🔗 <a href="https://www.clivescafe.com/">https://www.clivescafe.com/</a></p><h3><strong>Dukunnoo Wynwood</strong></h3><p>Caribbean comfort plates, jerk dishes, patties, cocktails.</p><p>🔗 <a href="https://dukunoowynwood.com/">https://dukunoowynwood.com/</a></p><h3><strong>JRK! (Fast Casual Jamaican)</strong></h3><p>The "Chipotle of Caribbean food" — build-your-own Jamaican bowls.</p><p>🔗 <a href="https://www.eatjrk.com/">https://www.eatjrk.com/</a></p><h3><strong>Manjay</strong></h3><p>(Also fits here — Haitian/Caribbean street food fusion)</p><p>🔗 <a href="https://www.manjayrestaurant.com/">https://www.manjayrestaurant.com/</a></p><h2>✨ <strong>Caribbean-American / Afro-Caribbean</strong></h2><h3><strong>Las Lap by Chef Kwame Onwuachi</strong></h3><p>A chic rum bar + Caribbean plates from James Beard-winner Kwame.</p><p>🔗 <a href="https://www.laslapnyc.com/">https://www.laslapnyc.com/</a></p><h3><strong>Mangrove</strong></h3><p>Caribbean-inspired, plant-forward, Miami-chic dining.</p><p>🔗 <a href="https://www.mangrovemiami.com/">https://www.mangrovemiami.com/</a></p><h2><strong>🇺🇸 Black American Restaurants</strong></h2><h3><strong>Red Rooster Overtown</strong></h3><p>Marcus Samuelsson\'s iconic Afro-American & Afro-Caribbean celebration.</p><p>🔗 <a href="https://www.redroosterovertown.com/">https://www.redroosterovertown.com/</a></p><h3><strong>Lil Greenhouse Grill</strong></h3><p>Chef-driven soul food — ribs, wings, mac & cheese, community staple.</p><p>🔗 <a href="https://www.lilgreenhousegrill.com/">https://www.lilgreenhousegrill.com/</a></p><h3><strong>Chef Tally Wood</strong></h3><p>Wings, smoked meats, southern + Caribbean fusion plates.</p><p>🔗 <a href="https://cheftallywood.com/">https://cheftallywood.com/</a></p>',
    largeLetter: true,
  },
]

export const sampleAuthors = [
  {
    userId: 'user1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    role: 'admin',
    username: 'alexj',
  },
  {
    userId: 'user2',
    name: 'Sam Martinez',
    email: 'sam@example.com',
    role: 'admin',
    username: 'samm',
  },
  {
    userId: 'user3',
    name: 'Jordan Lee',
    email: 'jordan@example.com',
    role: 'admin',
    username: 'jordanl',
  },
  {
    userId: 'user4',
    name: 'Melissa',
    email: 'melissa@example.com',
    role: 'admin',
    username: 'melissa',
  },
]

export const sampleContributors = [
  {
    userId: 'contributor1',
    name: 'Taylor Swift',
    email: 'taylor@example.com',
    role: 'contributor',
    username: 'taylors',
  },
  {
    userId: 'contributor2',
    name: 'Morgan Chen',
    email: 'morgan@example.com',
    role: 'contributor',
    username: 'morganc',
  },
]

